export type { Author, AuthorInput } from './AuthorTypes'
export type { Book, ReadDateBook, BookInput } from './BooksTypes'
export type { Series } from './SeriesTypes'
export type { Plot } from './PlotTypes'
export type { Search, IStatistic } from './SearchTypes'
