# Book data type
type Book {
  id: ID!
  authorID: ID!
  author: Author!
  title: String!
  rating: Float
  seriesID: ID
  series: Series
  tags: [Tags!]!
  seriesNumber: Int
  pages: Int
  notes: String
  description: String!
  readDate: [ReadDate!]!
  bookCover: String
  bookCoverThumbnail: String
  isAdditionalMediaExist: Boolean!
  additionalMedia: AllMediaForItem
}

input BookFilterInput {
  tagId: ID
  rating: Int
  year: Int
}

enum BookSortBy {
  TITLE_ASC
  TITLE_DESC
  RATING_ASC
  RATING_DESC
  DATE_ASC
  DATE_DESC
  AUTHOR_ASC
  AUTHOR_DESC
}

# Book data + total count type
type BooksResponse {
  totalCount: Int!
  books: [Book!]!
}

# input data for adding book
input BookInput {
  authorID: ID!
  title: String!
  rating: Float
  seriesID: ID
  seriesNumber: Int
  pages: Int
  notes: String
  description: String!
  readEnd: Date!
  plot: String
  bookCover: String
  bookCoverThumbnail: String
}

extend type Query {
  # Get a list of books
  getBooks(
    filter: BookFilterInput
    sort: BookSortBy = DATE_DESC
    page: Int = 1
    limit: Int = 50
  ): BooksResponse!

  # Get one book by id
  getOneBook(id: ID): Book
}

extend type Mutation {
  # Add book
  addBook(input: BookInput!): Book!
}
